run:
  concurrency: 4
  deadline: 5m
  issues-exit-code: 1
  tests: true

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: service/rice-box.go
      linters:
        - misspell
    - path-except: '(.+)_test\.go'
      linters:
        - misspell
linters:
  enable:
    - gosimple
    - staticcheck
    - unused
    - govet
    - unconvert
    - gocyclo
    - goimports
    - misspell
    - unparam
    - nakedret
    - bodyclose
    - dupl
